INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (1,'Klinika za pedijatriju','Pedijatrija',40,'+387 33 566 400');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (2,'Klinika za ginekologiju','Ginekologija i akušerstvo',10,'+ 387 33 250 250');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (3,'Porodiljska klinika','Ginekologija i akušerstvo',20,'+ 387 33 250 251');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (4,'Klinika za opštu i abdominalnu hirurgiju','Zgrada hirurgije',60,'+387 33 297 327');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (5,'Vaskularna i kardiohirurgija','Zgrada hirurgije',50,'+387 33 298 403');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (6,'Ortopedija i traumatologija','Zgrada hirurgije',50,'+ 387 33 297 630');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (7,'Intenzivna njega','Zgrada hirurgije',70,'+387 33 298 172');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (8,'Klinika za plućne bolesti','Interno',30,'+387 33 290 600');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (9,'Fizikalna medicina i rehabilitacija','Interno',20,'+387 33 297 000');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (10,'Klinika za bolesti srca krvnih žila i reumatizam','Kardiologija i reumatologija',40,'+387 33 297 524');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (11,'Psihijatrijska klinika','Neuropsihijatrija',10,'+387 33 297 352');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (12,'Neurološka klinika','Neuropsihijatrija',10,'+387 33 297-361');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (13,'Klinika za infektivne bolesti','Infektivno',30,'+387 33 297 250');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (14,'Klinika za onkologiju','Onkologija i radiologija',10,'+387 33 297 289');
INSERT INTO KLINIKA(JIB_KLINIKE,NAZIV,LOKACIJA,BROJ_KREVETA,BROJ_TEL) VALUES (15,'Radiologija','Onkologija i radiologija',10,'+387 33 297 533');
​